---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  vale:
    name: Run vale
    uses: ./.github/workflows/vale.yml

  spellcheck:
    name: Run spellcheck
    uses: ./.github/workflows/spellcheck.yml

  build:
    name: Build
    uses: ./.github/workflows/build.yml
